[package]
name = "lovebot"
version = "0.1.0"
edition = "2021"

[dependencies]
teloxide = { version = "0.5.3", features = ["macros", "auto-send"] }
log = "0.4.14"
pretty_env_logger = "0.4.0"
tokio = { version = "1.15.0", features = ["rt-multi-thread", "macros"] }
anyhow = "1.0.52"
rand = "0.8.4"
